//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TORRES_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class class_code_tb
    {
        public int classcodeId { get; set; }
        public string classcode { get; set; }
        public string email { get; set; }
        public string is_lock { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    }
}
