//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TORRES_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dynamicFooter
    {
        public int footerID { get; set; }
        public string footerDescription { get; set; }
        public string Links { get; set; }
        public string footerAddress { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    }
}
