//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TORRES_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class navbar_identifier_UI
    {
        public int navbarID { get; set; }
        public string navbarImage { get; set; }
        public string navbarRoute { get; set; }
        public Nullable<int> navbarIdentifier { get; set; }
    }
}
