//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TORRES_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_a_bug
    {
        public int bugID { get; set; }
        public string clientemail { get; set; }
        public string clientfullname { get; set; }
        public string bugCode { get; set; }
        public string bugTitle { get; set; }
        public string bugDescription { get; set; }
        public string bugLocation { get; set; }
        public string bugAttachedFile { get; set; }
        public Nullable<System.DateTime> startfixschedule { get; set; }
        public Nullable<System.DateTime> endfixschedule { get; set; }
        public string senttodev { get; set; }
        public string devmaintenance { get; set; }
        public string bugstatus { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    }
}
