//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TORRES_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Platform
    {
        public int id { get; set; }
        public string title { get; set; }
        public string alias { get; set; }
        public string access { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public string apiKeys { get; set; }
        public string platformImage { get; set; }
    }
}
