//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TORRES_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbClass
    {
        public int classId { get; set; }
        public string classname { get; set; }
        public string trainingUnder { get; set; }
        public string status { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    }
}
