//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TORRES_backend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ttcdbEntities : DbContext
    {
        public ttcdbEntities()
            : base("name=ttcdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminuser> adminusers { get; set; }
        public virtual DbSet<class_code_tb> class_code_tb { get; set; }
        public virtual DbSet<employeeUser> employeeUsers { get; set; }
        public virtual DbSet<report_a_bug> report_a_bug { get; set; }
        public virtual DbSet<training> trainings { get; set; }
        public virtual DbSet<user> users { get; set; }
    
        public virtual int update_session_handler(string email, Nullable<int> actionState)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var actionStateParameter = actionState.HasValue ?
                new ObjectParameter("actionState", actionState) :
                new ObjectParameter("actionState", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_session_handler", emailParameter, actionStateParameter);
        }
    }
}
