//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TORRES_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class training
    {
        public int id { get; set; }
        public string isonline { get; set; }
        public string trainingName { get; set; }
        public string SD { get; set; }
        public string FD { get; set; }
        public string WYL { get; set; }
        public string imageURL { get; set; }
        public string isstatus { get; set; }
        public string isforum { get; set; }
        public string islivechat { get; set; }
        public string capacity { get; set; }
        public string ispayment { get; set; }
        public Nullable<decimal> coursefee { get; set; }
        public string effort { get; set; }
        public string tLength { get; set; }
        public string categories { get; set; }
        public Nullable<System.DateTime> trainingStart { get; set; }
        public Nullable<System.DateTime> trainingEnd { get; set; }
        public string empAssignee { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    }
}
