//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TORRES_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_apikey_list
    {
        public int apiID { get; set; }
        public string apiKey { get; set; }
        public string isused { get; set; }
    }
}
